<%include file="trigger_defaults.yml"/>
<%include file="default.yml"/>

job_description: Triggered when a downstream patch is pushed internally (pull request)
artifactNumToKeep: 10
githubProject: "https://github.com/dimtruck/OpenStackProject/"
scm:
  gitURL: "ssh://git@github.com/dimtruck/OpenStackProject"
  gitBranch: "<%text>${sha1}</%text>"
  refSpec: "+refs/pull/*:refs/remotes/origin/pr/*"
  extensions:
    cleanbeforecheckout: True
triggers:
  github_pr:
    spec: "H/5 * * * *"
    adminlist: "dimtruck"
    orglist: internal
    cron: "H/5 * * * *"
    triggerPhrase: recheck
    useGitHubHooks: True
    whitelist: dimtruck
triggerBuilder:
  parameter:
    name: "InternalDeployment"
    value: True
  properties: |
              <%text>sha1=${ghprbActualCommit}</%text>
  projects: raxio_jobs_data_downstream_patch_build_flow