<%include file="trigger_defaults.yml"/>
<%include file="default.yml"/>

job_description: Triggered when an upstream patch is pushed upstream
artifactNumToKeep: 10
buildParams:
  - paramName: PublicRepo
    paramValue: "ssh://git@github.com/dimtruck/raxio-cd-demo.git"
    paramDesc:  Public repository (Openstack)
    paramType: string
  - paramName: PublicRepoBranch
    paramValue: "Public repository branch (Openstack/master)"
    paramDesc:  "Public repository branch (Openstack/master)"
    paramType: string  
  - paramName: PrivateRepo
    paramValue: "ssh://git@github.com/dimtruck/raxio-cd-demo.git"
    paramDesc:  Private repository (Company specific)
    paramType: string
  - paramName: PrivateRepoBranch
    paramValue: "Private repository branch to push to (Company specific)"
    paramDesc:  "Private repository branch to push to (Company specific)"
    paramType: string
envInjectJobProperty:
  content: |
           echo &quot;GERRIT_REFSPEC:$GERRIT_REFSPEC&quot; 
           echo &quot;GERRIT_BRANCH:$GERRIT_BRANCH&quot;
scm:
  gitURL: "ssh://dimalg@raxio2015-gerrit.dimitryushakov.com:29418/raxio-cd-demo"
  gitBranch: "$GERRIT_REFSPEC"
  refSpec: "refs/changes/*:refs/changes/*"
  extensions:
    buildChooserSetting: True
triggers:
  gerrit:
    compareType: PLAIN
    pattern: "raxio-cd-demo"
    branch_pattern: master
    commentAddedCommentContains: "recheck.*"
shell_build_command: 
  - build: |
           <%text>#!/bin/bash
           # Set up a build branch for Arbor-Build to use
           gerrit_internal_branch=&quot;${GERRIT_REFSPEC//\//-}&quot;  

           git remote add internal_repo ${PrivateRepo}|| echo &quot;PrivateRepo set&quot;
           git fetch internal_repo -a
           git branch -D internal_repo/$gerrit_internal_branch || echo &quot;branch:$gerrit_internal_branch does not exist... creating&quot;
           git checkout -b $gerrit_internal_branch
           git push internal_repo $gerrit_internal_branch -f
           echo &quot;gerrit_internal_branch=$gerrit_internal_branch&quot; &gt;&gt; gerrit_internal_branch.txt</%text>
envInjectBuilder: "gerrit_internal_branch.txt"                     
triggerBuilder:
  parameter:
    name: "GerritDeployment"
    value: True
  properties: |
              <%text>deploy=true
              DontPush=false
              PrivateRepo=${PrivateRepo}
              UpstreamBranch=${gerrit_internal_branch}
              PrivateRepoBranch=${PrivateRepoBranch}</%text>
  projects: raxio_jobs_data_upstream_patch_build_flow